# .github/workflows/create-pr.yml
name: Create Pull Request on Branch Push

on:
  push:
    branches-ignore: # Игнорируем главную ветку
      - main
      # Можете добавить другие ветки, для которых не нужно создавать PR, например 'develop'

jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    # Запускаем только если ветка не main (дополнительная проверка)
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Важно: fetch-depth: 0 нужен, чтобы gh мог сравнить ветки
        with:
          fetch-depth: 0

      - name: Create Pull Request using GitHub CLI
        env:
          # Используем стандартный токен GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Получаем имя текущей ветки (например, feature/new-button)
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "Checking for existing PR for branch: $BRANCH_NAME"
          # Проверяем, есть ли уже открытый PR для этой ветки
          gh pr list --head "$BRANCH_NAME" --base "main" --state "open" --json "number" -q ". | length" > pr_count.txt
          COUNT=$(cat pr_count.txt)

          if [ "$COUNT" -eq "0" ]; then
            echo "No existing PR found. Creating a new PR..."
            # Пытаемся создать PR. Если между ветками нет разницы, команда может вернуть ошибку, но это ок.
            gh pr create \
              --base "main" \
              --head "$BRANCH_NAME" \
              --title "Merge changes from $BRANCH_NAME into main" \
              --body "Automated PR created for branch \`$BRANCH_NAME\`. Please review and merge." \
              --label "autogenerated-pr" || echo "Could not create PR. Maybe no changes or PR already exists?"
              # Добавьте --assignee @me или --reviewer user1,user2 если нужно
            echo "PR creation process finished."
          else
            echo "PR already exists for branch $BRANCH_NAME. Skipping creation."
          fi