# .github/workflows/create-pr.yml
name: Create Pull Request on Branch Push

on:
  push:
    branches-ignore:
      - main

jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    # ---> ДОБАВЬТЕ ЭТОТ БЛОК <---
    permissions:
      contents: read       # Нужно для checkout
      pull-requests: write # Нужно для gh pr create
    # ---> КОНЕЦ БЛОКА <---

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          echo "Checking for existing PR for branch: $BRANCH_NAME"
          gh pr list --head "$BRANCH_NAME" --base "main" --state "open" --json "number" -q ". | length" > pr_count.txt
          COUNT=$(cat pr_count.txt)

          if [ "$COUNT" -eq "0" ]; then
            echo "No existing PR found. Creating a new PR..."
            gh pr create \
              --base "main" \
              --head "$BRANCH_NAME" \
              --title "Merge changes from $BRANCH_NAME into main" \
              --body "Automated PR created for branch \`$BRANCH_NAME\`. Please review and merge." \
              || echo "Could not create PR. Maybe no changes or PR already exists?"
            echo "PR creation process finished."
          else
            echo "PR already exists for branch $BRANCH_NAME. Skipping creation."
          fi