# .github/workflows/pr-checks.yml
name: PR Checks

on:
  pull_request:
    branches: [ main ] # Запускать для PR в main
    types: [ opened, synchronize ] # При открытии и обновлении PR

jobs:
  validate_code: # Назовем задачу осмысленно
    name: Validate Code (PHP & HTML) # Имя, которое будет отображаться в GitHub UI
    runs-on: ubuntu-latest
    steps:
      # 1. Получаем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # --- PHP Syntax Check ---
      # 2. Настраиваем окружение PHP (хорошая практика, даже если php есть по умолчанию)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # УКАЖИТЕ ВЕРСИЮ PHP, которую вы используете на Beget!
          extensions: none # Доп. расширения не нужны для -l
          tools: none

      # 3. Запускаем проверку синтаксиса для всех .php файлов
      - name: Check PHP Syntax (Lint)
        run: |
          echo "Linting PHP files..."
          # Находим все файлы .php, исключая папку vendor (если вы ее используете)
          # и для каждого выполняем php -l
          find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l

      # --- HTML Validation ---
      # 4. Используем Action для валидации HTML
      - name: Validate HTML files
        uses: technote-space/html-validate-action@v2
        with:
          TARGETS: '**/*.html' # Отступ в 2 пробела
          IGNORE: '.git'      # Отступ в 2 пробела